export const colleges = [
    {
        name: 'Bourns College of Engineering',
        departments: [
            'Biochemistry',
            'Bioengineering',
            'Chemical Engineering',
            'Computer Science',
            'Computer Engineering',
            'Data Science',
            'Environmental Engineering',
            'Electrical Engineering',
            'Materials Science and Engineering',
            'Mechanical Engineering',
        ],
    },
    {
        name: 'College of Humanities, Arts, and Social Sciences',
        departments: [
            'Art',
            'History of Art',
            'Creative Writing',
            'Dance',
            'Music',
            'Theatre, Film, and Digital Production',
            'Comparative Literature and Languages',
            'English',
            'Gender and Sexuality Studies',
            'Hispanic Studies',
            'History',
            'Media and Cultural Studies',
            'Philosophy',
            'Religious Studies',
            'Anthropology',
            'Economics',
            'Ethnic Studies',
            'Political Science',
            'Psychology',
            'Sociology',
        ],
    },
    {
        name: 'College of Natural and Agricultural Sciences',
        departments: [
            'Botany & Plant Sciences',
            'Entomology',
            'Environmental Sciences',
            'Nematology',
            'Biochemistry',
            'Evolution, Ecology, and Organismal Biology',
            'Molecular, Cell and Systems Biology',
            'Microbiology & Plant Pathology',
            'Chemistry',
            'Earth Sciences',
            'Mathematics',
            'Physics and Astronomy',
            'Statistics',
        ],
    },
];
